version: 0.2
phases:
  build:
    commands:
      - set -eu
      - cd "$CODEBUILD_SRC_DIR/$TF_DIR"
      - terraform init -lock=false -input=false -reconfigure -backend-config="${BACKEND_FILE}"
      - terraform plan -no-color -input=false -var-file="${TFVARS_FILE}" -var-file="${SHARED_VARS}" -out=tfplan
      - terraform apply -no-color -input=false tfplan
